### ISSUE TITLE
IOptionsXXX<> interfaces don't appear to bind to the source

### ISSUE THREAD

**Issue by Nihlus** [riezebosch/CommandLiners#4]
I'm currently trying to integrate CommandLiners.Posix into my application, but I can't seem to get any of the `IOptions<>` variants to give me a properly bound instance of the options type. I can manually bind one as shown in the example code, but all of the interface variants produce instances with all-default values.

**Comment by riezebosch** [comment]
Have never tried that! Do you have a more complete but isolated example I can try out?

**Comment by Nihlus** [comment]
Sure thing! Here's a minimal example.

```cs
using System;
using CommandLiners;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

var builder = Host.CreateApplicationBuilder(args);
builder.Configuration.AddCommandLineOptions
(
    args.ToPosix<ExampleOptions>
    (
        map => map
            .Add("some-flag", o => o.SomeFlag)
            .Add("some-other-flag", o => o.SomeOtherFlag)
    )
);

// uncomment for workaround
// builder.Services.Configure<ExampleOptions>(o => builder.Configuration.Bind(o));

var app = builder.Build();

var config = app.Services.GetRequiredService<IOptions<ExampleOptions>>().Value;

Console.WriteLine(config);

public record ExampleOptions(bool SomeFlag, bool SomeOtherFlag)
{
    public ExampleOptions()
        : this(false, false)
    {

    }
}
```

Build with references to `Microsoft.Extensions.Hosting` and `CommandLiners.Posix`. You can uncomment the marked line for a workaround that enables "normal" access to configured options as described.

**Comment by riezebosch** [comment]
I'm looking into that but it seems to me that it also doesn't work for the default command line configuration provider.

Update, this also seems to do the trick:

```csharp
builder.Services.AddOptions<ExampleOptions>().BindConfiguration("");
```

and also: 

```csharp
builder.Services.AddOptions<ExampleOptions>().Bind(builder.Configuration);
```

**Comment by Nihlus** [comment]
Oh, you know what, I'm silly. My bad, I completely forgot I was doing `Configure<>` calls for all other option types as well. All good!

**Comment by riezebosch** [comment]
to be honest, nowadays you can probably achieve the same without my package by specifying the mapping on the `AddCommandLine` overload:

```csharp
builder.Configuration.AddCommandLine(args, new Dictionary<string, string>
        {
            ["-s"] = "SomeFlag",
            ["--some-other-flag"] = "SomeOtherFlag"
        });
```
